apiVersion: v1
kind: Service
metadata:
  name: autodeploy88
  namespace: namespace-workflow-1708358871007
spec:
  type: LoadBalancer
  selector:
    app: autodeploy88
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000